import { Fish } from "./fish.model.tsx";

export const fishData: Fish[] = [
    {
      id: 0,
      name: "Bar",
      scientificName: "Dicentrarchus labrax",
      // category: "Démersaux",
      minSizeCm: "25",
      faoCode: "BSS",
      physicalDescription: "Corps rond, très grosse tête, grande bouche, dos sombre, ventre argenté. Pointe de la pectorale au milieu des 2 dorsales, la 2ème nageoire dorsale et l’anale sont de taille similaire, pinnules jaunes, bordées d’un fin liseré noir, large carène sur le pédoncule caudal.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/BSS/0',
      additionalImages: [
        { id: 1, url: '/api/image/BSS/1' },
        { id: 2, url: '/api/image/BSS/2' },
        { id: 3, url: '/api/image/BSS/3' },
        { id: 4, url: '/api/image/BSS/4' },
      ]
    },
    {
      id: 1,
      name: "Sparaillon",
      scientificName: "Diplodus annularis",
      // category: "Scombridés",
      minSizeCm: "12",
      faoCode: "ANN",
      physicalDescription: "Corps ovale, dos et ventre bombés, tête courte, la bouche, petite et arrondie se termine en avant de l’œil, petites dents pointues. Couleur bronze-argenté. Les nageoires pelviennes et l’annale sont jaunes, la tache noire entoure le pédoncule caudal. Confusion possible avec le SAR.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/ANN/0',
      additionalImages: [
        { id: 1, url: '/api/image/ANN/1' },
        { id: 2, url: '/api/image/ANN/2' },
        { id: 3, url: '/api/image/ANN/3' },
        { id: 4, url: '/api/image/ANN/4' },
      ]
    },
    {
      id: 2,
      name: "Sar à Museau Pointu",
      scientificName: "Diplodus puntazzo",
      // category: "Démersaux",
      minSizeCm: "18",
      faoCode: "SHR",
      physicalDescription: "Corps ovale, assez épais, tête petite et museau arrondi, grosses lèvres, dos et ventre arrondis. Couleur argent, bronze et rosé. Il est zébré de 5 bandes larges depuis l’arrière de la tête jusqu’au pédoncule caudal, 1 nageoire dorsale.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SHR/0',
      additionalImages: [
        { id: 1, url: '/api/image/SHR/1' },
        { id: 2, url: '/api/image/SHR/2' },
        { id: 3, url: '/api/image/SHR/3' },
        { id: 4, url: '/api/image/SHR/4' },
      ]
    },
    {
      id: 3,
      name: "Sar Commun",
      scientificName: "Diplodus sargus",
      // category: "Démersaux",
      minSizeCm: "23",
      faoCode: "SWA",
      physicalDescription: "Corps ovale, peu épais, tête courte, museau pointu, bouche munie d’incisives coupantes, couleur gris-argenté zébré de rayures verticales noires. Dos rond, 1 nageoire dorsale, les pelviennes sont de couleur blanc et noir, la partie ventrale est moins bombée que chez la dorade grise, il a une tache noire sur le pédoncule caudal. Il existe plusieurs espèces (à museau pointu, à tête noire... ). Confusion possible avec la dorade grise.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SWA/0',
      additionalImages: [
        { id: 1, url: '/api/image/SWA/1' },
        { id: 2, url: '/api/image/SWA/2' },
        { id: 3, url: '/api/image/SWA/3' },
        { id: 4, url: '/api/image/SWA/4' },
      ]
    },
    {
      id: 4,
      name: "Sar à Tête Noire",
      scientificName: "Diplodus vulgaris",
      // category: "Démersaux",
      minSizeCm: "18",
      faoCode: "CTB",
      physicalDescription: "Corps ovale, peu épais, tête pointue, couleur gris-argenté, 1 nageoire dorsale. Il a une tache noire très marquée sur la nuque et sur le pédoncule caudal. Il existe plusieurs espèces : à museau pointu, commun... ils peuvent être confondus en eux.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/CTB/0',
      additionalImages: [
        { id: 1, url: '/api/image/CTB/1' },
        { id: 2, url: '/api/image/CTB/2' },
        { id: 3, url: '/api/image/CTB/3' },
        { id: 4, url: '/api/image/CTB/4' },
      ]
    },
    {
      id: 5,
      name: "Anchois",
      scientificName: "Engraulis encrasicolus",
      // category: "Pélagiques / Migrateurs",
      minSizeCm: "9/13",
      faoCode: "ANE",
      physicalDescription: "Corps ovale qui est moins large que la sardine, une tête reconnaissable, l’œil à l’extrémité de la tête, une très grande ouverture des mâchoires, des opercules très larges, dos bleu sombre, à l’examen de la tête on ne peut pas confondre les anchois avec les autres poissons bleus.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/ANE/0',
      additionalImages: [
        { id: 1, url: '/api/image/ANE/1' },
        { id: 2, url: '/api/image/ANE/2' },
        { id: 3, url: '/api/image/ANE/3' },
        { id: 4, url: '/api/image/ANE/4' },
      ]
    },
    {
      id: 6,
      name: "Mérou",
      scientificName: "Mycteroperca rubra",
      // category: "Pélagiques / Migrateurs",
      minSizeCm: '45',
      faoCode: "BSX",
      physicalDescription: "Corps rond, très grosse tête, grande bouche, dos sombre, ventre argenté. Pointe de la pectorale au milieu des 2 dorsales, la 2ème nageoire dorsale et l’anale sont de taille similaire, pinnules jaunes, bordées d’un fin liseré noir, large carène sur le pédoncule caudal.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/BSX/0',
      additionalImages: [
        { id: 1, url: '/api/image/BSX/1' },
        { id: 2, url: '/api/image/BSX/2' },
        { id: 3, url: '/api/image/BSX/3' },
        { id: 4, url: '/api/image/BSX/4' },
      ]
    },
    {
      id: 7,
      name: "Marbré",
      scientificName: "Lithognathus mormyrus",
      // category: "Amphihalins",
      minSizeCm: "20",
      faoCode: "SSB",
      physicalDescription: "Corps ovale, épais, grosse tête, œil bien en retrait de la bouche, dos plus bombé que le ventre. Couleur argentée avec des bandes verticales marron, 1 nageoire dorsale. Confusion possible avec le pageot commun.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SSB/0',
      additionalImages: [
        { id: 1, url: '/api/image/SSB/1' },
        { id: 2, url: '/api/image/SSB/2' },
        { id: 3, url: '/api/image/SSB/3' },
        { id: 4, url: '/api/image/SSB/4' },
      ]
    },
    {
      id: 8,
      name: "Merlu Commun",
      scientificName: "Merluccius merluccius",
      // category: "Démersaux",
      minSizeCm: "20",
      faoCode: "HKE",
      physicalDescription: "Corps rond, épais, grande tête et grande bouche munie de petites dents acérées, la mâchoire se termine sous le milieu de l’œil. Dos marron sombre à gris suivant le mode de pêche, ventre argenté, 2 nageoires dorsales longues, ligne latérale fine et sombre. Confusion possible avec le merlan de chalut.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/HKE/0',
      additionalImages: [
        { id: 1, url: '/api/image/HKE/1' },
        { id: 2, url: '/api/image/HKE/2' },
        { id: 3, url: '/api/image/HKE/3' },
        { id: 4, url: '/api/image/HKE/4' },
      ]
    },
    {
      id: 9,
      name: "Rouget Barbet de Roche",
      scientificName: "Mullus surmuletus",
      // category: "Benthiques",
      minSizeCm: "11",
      faoCode: "MUR",
      physicalDescription: "Corps ovale, tête moyenne, la bouche se termine à la perpendiculaire de l’avant de l’œil, front busqué, dos et flancs rouge dégradé, ventre blanc, 2 nageoires dorsales zébrées et colorées, 3 lignes longitudinales jaunes visibles sur les flancs (sur les poissons pêchés aux filets). œil rouge, iris noir, présence de 2 longs barbillons blancs. Peuvent être confondus avec le rouget du Sénégal, le rouget à tache noire... Les rougets pêchés au chalut sont très souvent abîmés.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/MUR/0',
      additionalImages: [
        { id: 1, url: '/api/image/MUR/1' },
        { id: 2, url: '/api/image/MUR/2' },
        { id: 3, url: '/api/image/MUR/3' },
        { id: 4, url: '/api/image/MUR/4' },
      ]
    },
    {
      id: 10,
      name: "Pageot Acarné",
      scientificName: "Pagellus acarne",
      // category: "Démersaux",
      minSizeCm: "17",
      faoCode: "SBA",
      physicalDescription: "Corps ovale, pas très épais, tête plus fine que chez les autres sparidés, la bouche à l’aplomb du milieu de l’œil, le dos et les nageoires sont rouge orangé, 1 nageoire dorsale, il a une petite tache noire sur la nageoire pectorale*. Confusion possible avec avec la dorade rose (tache noire sur la ligne latérale) et le pageot commun.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SBA/0',
      additionalImages: [
        { id: 1, url: '/api/image/SBA/1' },
        { id: 2, url: '/api/image/SBA/2' },
        { id: 3, url: '/api/image/SBA/3' },
        { id: 4, url: '/api/image/SBA/4' },
      ]
    },
    {
      id: 11,
      name: "Dorade Rose",
      scientificName: "Pagellus bogaraveo",
      // category: "Démersaux",
      minSizeCm: "-",
      faoCode: "SBR",
      physicalDescription: "Corps ovale, assez épais, tête courte, bouche à l’aplomb de l’avant de l’œil qui est gros, dos et ventre arrondis, elle a une tache noire sur la ligne latérale. Le dos est rouge orangé ainsi que les nageoires pectorales et caudale, la partie ventrale est argentée. Confusion possible avec le pageot acarne et le pageot commun.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SBR/0',
      additionalImages: [
        { id: 1, url: '/api/image/SBR/1' },
        { id: 2, url: '/api/image/SBR/2' },
        { id: 3, url: '/api/image/SBR/3' },
        { id: 4, url: '/api/image/SBR/4' },
      ]
    },
    {
      id: 12,
      name: "Pageot Commun",
      scientificName: "Pagellus erythrinus",
      // category: "Démersaux",
      minSizeCm: "15",
      faoCode: "PAC",
      physicalDescription: "Corps ovale, grosse tête, museau pointu et allongé, œil bien en retrait de la bouche, marque rouge foncé sur l’opercule. Couleur rose et argentée, 1 nageoire dorsale. Confusion possible avec la dorade rose, le pageot acarne, le pagre.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/PAC/0',
      additionalImages: [
        { id: 1, url: '/api/image/PAC/1' },
        { id: 2, url: '/api/image/PAC/2' },
        { id: 3, url: '/api/image/PAC/3' },
        { id: 4, url: '/api/image/PAC/4' },
      ]
    },
    {
      id: 13,
      name: "Pagre Commun",
      scientificName: "Pagrus pagrus",
      // category: "Démersaux",
      minSizeCm: "18",
      faoCode: "RPG",
      physicalDescription: "Corps ovale, massif. Grosse tête, front busqué, l’œil en retrait de la bouche, une ligne rouge sombre sur l’opercule. De couleur rose/rouge et argentée. Ligne latérale plus sombre et légèrement arquée, les nageoires pectorales sont longues, 1 nageoire dorsale, la caudale a des taches blanches aux extrémités.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/RPG/0',
      additionalImages: [
        { id: 1, url: '/api/image/RPG/1' },
        { id: 2, url: '/api/image/RPG/2' },
        { id: 3, url: '/api/image/RPG/3' },
        { id: 4, url: '/api/image/RPG/4' },
      ]
    },
    {
      id: 14,
      name: "Cernier Atlantique",
      scientificName: "Polyprion americanus",
      // category: "EEP",
      minSizeCm: "45",
      faoCode: "WRF",
      physicalDescription: "Corps ovale, très épais, tête osseuse, un décroché entre le front et le dos, mandibule saillante, très grande bouche, couleur grise, ligne latérale fine, 1 dorsale, toutes les nageoires sont sombres, 2 épines anales. Confusion très facile avec le mérou.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/WRF/0',
      additionalImages: [
        { id: 1, url: '/api/image/WRF/1' },
        { id: 2, url: '/api/image/WRF/2' },
        { id: 3, url: '/api/image/WRF/3' },
        { id: 4, url: '/api/image/WRF/4' },
      ]
    },
    {
      id: 15,
      name: "Sardine",
      scientificName: "Sardina pilchardus",
      // category: "Pélagiques / Migrateurs",
      minSizeCm: "11",
      faoCode: "PIL",
      physicalDescription: "Corps ovale, épais, couleur bleue / verte, argentée, 1 nageoire dorsale, la mâchoire s’arrête sous le milieu de l’œil, les opercules sont striés marqués en leur milieu d’un petit point noir. Les écailles se détachent facilement et on observe alors des taches noires sur la ligne latérale.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/PIL/0',
      additionalImages: [
        { id: 1, url: '/api/image/PIL/1' },
        { id: 2, url: '/api/image/PIL/2' },
        { id: 3, url: '/api/image/PIL/3' },
        { id: 4, url: '/api/image/PIL/4' },
      ]
    },
    {
      id: 16,
      name: "Maquereau",
      scientificName: "Scomber scombrus",
      // category: "Pélagiques / Migrateurs",
      minSizeCm: "18",
      faoCode: "MAC",
      physicalDescription: "Corps ovale, lisse, épais, couleurs variées, dos bleu, gris, vert, rayures noires, ventre argenté, petites écailles, 2 nageoires dorsales, pectorales courtes, présence de pinnules. Il peut être confondu très facilement avec le maquereau blanc (ex espagnol).",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/MAC/0',
      additionalImages: [
        { id: 1, url: '/api/image/MAC/1' },
        { id: 2, url: '/api/image/MAC/2' },
        { id: 3, url: '/api/image/MAC/3' },
        { id: 4, url: '/api/image/MAC/4' },
      ]
    },
    {
      id: 17,
      name: "Sole Commune",
      scientificName: "Solea vulgaris",
      // category: "Benthiques",
      minSizeCm: "20",
      faoCode: "SOL",
      physicalDescription: "Corps plat et ovale, petite tête, couleur beige à marron, selon son biotope présence de taches noires sur le dos, ventre blanc, très petites écailles. Une tache noire sur la pectorale, 1 dorsale qui commence de la queue et se termine au niveau du milieu de l’œil. Elle peut être confondue avec la sole sénégalaise, blonde ou les céteaux.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SOL/0',
      additionalImages: [
        { id: 1, url: '/api/image/SOL/1' },
        { id: 2, url: '/api/image/SOL/2' },
        { id: 3, url: '/api/image/SOL/3' },
        { id: 4, url: '/api/image/SOL/4' },
      ]
    },
    {
      id: 18,
      name: "Dorade Royale",
      scientificName: "Sparus aurata",
      // category: "EEP",
      minSizeCm: "20",
      faoCode: "SBG",
      physicalDescription: "Corps ovale, tête colorée (jaune, noire, orange sur l’opercule), la bouche est à l’aplomb de l’avant de l’œil, une ‘’couronne’’ est bien visible au niveau des yeux, dos arrondi, ventre plat, couleur argenté clair à sombre, 1 nageoire dorsale, et une ligne sombre sur l’ extrémité de la caudale.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/SBG/0',
      additionalImages: [
        { id: 1, url: '/api/image/SBG/1' },
        { id: 2, url: '/api/image/SBG/2' },
        { id: 3, url: '/api/image/SBG/3' },
        { id: 4, url: '/api/image/SBG/4' },
      ]
    },
    {
      id: 19,
      name: "Chinchard",
      scientificName: "Trachurus trachurus",
      // category: "Pélagiques / Migrateurs",
      minSizeCm: "15",
      faoCode: "HOM",
      physicalDescription: "Corps ovale, épais, la bouche se termine à l’aplomb du milieu de l’œil, couleurs : bleue, gris verdâtre, argentée, taches noires à l’arrière des opercules, 2 nageoires dorsales, les pectorales dépassent la 2ème dorsale, 2 courtes mais fortes épines anales. Les lignes latérales du chinchard sont constituées d’écailles épaisses en chevrons : les scutelles sont plus larges que chez le HMM, présence de lignes latérales secondaire longues. Les différentes espèces de chinchards se distinguent par la hauteur des scutelles et la position de la brisure de la ligne latérale.",
      bodyType: { id: 0, name: '', description: '' },
      fins: [{ id: 0, type: '', shape: '', color: '', size: '' }],
      eyes: [{ id: 0, color: '', size: '', position: '' }],
      img: '/api/image/HOM/0',
      additionalImages: [
        { id: 1, url: '/api/image/HOM/1' },
        { id: 2, url: '/api/image/HOM/2' },
        { id: 3, url: '/api/image/HOM/3' },
        { id: 4, url: '/api/image/HOM/4' },
      ]
    }
  ];